<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.3" />
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="jQuery.Validation" Version="1.21.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Data.SqlClient.SNI.runtime" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.81.0" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0" />
    <PackageReference Include="Modernizr" Version="2.6.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="WebGrease" Version="1.5.2" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.2.1" />
    <PackageReference Include="Antlr4" Version="4.6.6" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Global.asax.cs">
      <DependentUpon>Global.asax</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="Scripts\jquery-3.4.1.intellisense.js" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Project_Readme.txt" />
  </ItemGroup>
  <Target Name="CopySQLClientNativeBinaries" AfterTargets="AfterBuild">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll" DestinationFiles="$(OutputPath)Microsoft.Data.SqlClient.SNI.x64.dll" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll" DestinationFiles="$(OutputPath)Microsoft.Data.SqlClient.SNI.x86.dll" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll" DestinationFolder="$(OutputPath)x64\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll" DestinationFolder="$(OutputPath)x86\" SkipUnchangedFiles="true" />
  </Target>
</Project>