# terraform.auto.tfvars
# dev.tfvars - Development Environment Configuration
# This file contains NON-SECRET configuration values
# It is safe to commit this file to Git
#
# NOTE: SQL password is now AUTO-GENERATED by Terraform using random_password
# You don't need to provide sql_admin_password anymore!
# The password is automatically stored in Azure Key Vault

# Basic Configuration
resource_group_name = "rg-contoso-university-upgraded-dev"
location            = "East US"
environment         = "dev"
app_name            = "contoso-university-upgraded"

# Pricing Tiers
app_service_sku  = "B1"   # Basic tier for dev (use P1V2+ for production)
sql_database_sku = "S0"   # Standard tier

# SQL Configuration (non-secret)
sql_admin_username = "sqladmin"

# Network Configuration
# Add your IP addresses here to access SQL Server from your machine
# Example: allowed_ip_addresses = ["203.0.113.1", "198.51.100.1"]
allowed_ip_addresses = []

# Authentication Configuration
enable_entra_id_auth = false

# Resource Tags
tags = {
  Application = "ContosoUniversityUpgraded"
  Environment = "Development"
  ManagedBy   = "Terraform"
  Repository  = "dotnet-migration-copilot-samples"
}

# Notes:
# - This file is committed to Git (safe, no secrets)
# - SQL password is AUTO-GENERATED and stored in Key Vault
# - For Entra ID secrets, use GitHub Secrets or environment variables
# - To use this file: terraform apply -var-file=dev.tfvars
