variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
  default     = "rg-contoso-university"
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "East US"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "app_name" {
  description = "Application name"
  type        = string
  default     = "contoso-university"
}

variable "app_service_sku" {
  description = "App Service Plan SKU"
  type        = string
  default     = "B1" # Basic tier for dev, use P1V2 or higher for production
}

variable "sql_admin_username" {
  description = "SQL Server administrator username"
  type        = string
  default     = "sqladmin"
}

# Note: sql_admin_password is now auto-generated by random_password resource
# No need to provide it manually - it's created and stored in Key Vault automatically

variable "sql_database_sku" {
  description = "SQL Database SKU"
  type        = string
  default     = "S0" # Standard tier
}

variable "allowed_ip_addresses" {
  description = "List of allowed IP addresses for SQL firewall"
  type        = list(string)
  default     = []
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default = {
    Application = "ContosoUniversity"
    ManagedBy   = "Terraform"
  }
}

variable "enable_entra_id_auth" {
  description = "Enable Microsoft Entra ID authentication"
  type        = bool
  default     = false
}

variable "entra_client_id" {
  description = "Microsoft Entra ID Application (Client) ID"
  type        = string
  default     = ""
}

variable "entra_tenant_id" {
  description = "Microsoft Entra ID Directory (Tenant) ID"
  type        = string
  default     = ""
}

variable "entra_client_secret" {
  description = "Microsoft Entra ID Client Secret"
  type        = string
  sensitive   = true
  default     = ""
}
