# Contoso University - Setup Without Service Principal
# Use this if you don't have permissions to create Service Principals

$ErrorActionPreference = "Stop"

Write-Host "?? Contoso University - Local Setup" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script sets up for local deployment using your Azure credentials" -ForegroundColor Yellow
Write-Host ""

# Check if Azure CLI is installed
try {
    az version | Out-Null
    Write-Host "? Azure CLI found" -ForegroundColor Green
} catch {
    Write-Host "? Azure CLI is not installed. Please install it first:" -ForegroundColor Red
    Write-Host "   https://docs.microsoft.com/cli/azure/install-azure-cli-windows" -ForegroundColor Yellow
    exit 1
}

# Check if Terraform is installed
try {
    terraform version | Out-Null
    Write-Host "? Terraform found" -ForegroundColor Green
} catch {
    Write-Host "? Terraform is not installed. Please install it first:" -ForegroundColor Red
    Write-Host "   https://www.terraform.io/downloads" -ForegroundColor Yellow
    exit 1
}

Write-Host ""

# Login to Azure
Write-Host "?? Logging in to Azure..." -ForegroundColor Cyan
Write-Host "    (This will open a browser window)" -ForegroundColor Yellow
az login

if ($LASTEXITCODE -ne 0) {
    Write-Host "? Azure login failed" -ForegroundColor Red
    exit 1
}

# Get subscription info
$subscriptionId = az account show --query id -o tsv
$subscriptionName = az account show --query name -o tsv
$userEmail = az account show --query user.name -o tsv

Write-Host ""
Write-Host "? Logged in successfully!" -ForegroundColor Green
Write-Host "   User: $userEmail" -ForegroundColor White
Write-Host "   Subscription: $subscriptionName" -ForegroundColor White
Write-Host "   Subscription ID: $subscriptionId" -ForegroundColor White
Write-Host ""

Write-Host "??  SQL Password Configuration" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host "SQL password is AUTO-GENERATED by Terraform!" -ForegroundColor Green
Write-Host "  - No need to provide a password" -ForegroundColor White
Write-Host "  - Password is automatically created during deployment" -ForegroundColor White
Write-Host "  - Stored securely in Azure Key Vault" -ForegroundColor White
Write-Host ""

# Get user's public IP for SQL firewall
Write-Host "?? Getting your public IP address..." -ForegroundColor Cyan
try {
    $publicIp = (Invoke-WebRequest -Uri "https://api.ipify.org" -UseBasicParsing).Content.Trim()
    Write-Host "   Your IP: $publicIp" -ForegroundColor White
    Write-Host "   (This will be added to SQL firewall rules)" -ForegroundColor Yellow
} catch {
    Write-Host "??  Could not detect public IP" -ForegroundColor Yellow
    $publicIp = ""
}
Write-Host ""

# Prompt for app name
$defaultAppName = "contoso-university-$($userEmail.Split('@')[0].ToLower())"
$appName = Read-Host "Enter app name (default: $defaultAppName)"
if ([string]::IsNullOrWhiteSpace($appName)) {
    $appName = $defaultAppName
}

# Create terraform.tfvars (if needed for Entra ID secrets only)
Write-Host ""
Write-Host "?? No terraform.tfvars needed!" -ForegroundColor Cyan
Write-Host "   SQL password is auto-generated" -ForegroundColor White
Write-Host "   Configuration is in dev.tfvars" -ForegroundColor White
Write-Host ""
Push-Location -Path "..\..\infrastructure\terraform"

# Initialize Terraform
Write-Host "?? Initializing Terraform..." -ForegroundColor Cyan
terraform init

if ($LASTEXITCODE -ne 0) {
    Write-Host "? Terraform initialization failed" -ForegroundColor Red
    Pop-Location
    exit 1
}

Write-Host ""
Write-Host "? Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "?? Configuration Summary:" -ForegroundColor Yellow
Write-Host "========================" -ForegroundColor Yellow
Write-Host "Resource Group: rg-$appName-dev" -ForegroundColor White
Write-Host "App Name: $appName" -ForegroundColor White
Write-Host "Location: East US" -ForegroundColor White
Write-Host "SQL Admin: sqladmin" -ForegroundColor White
Write-Host "SQL Password: AUTO-GENERATED (stored in Key Vault)" -ForegroundColor Green
Write-Host "Your IP: $publicIp" -ForegroundColor White
Write-Host ""
Write-Host "?? Next Steps:" -ForegroundColor Cyan
Write-Host "1. Review dev.tfvars file (edit if needed)" -ForegroundColor White
Write-Host "2. Run: terraform plan -var-file=dev.tfvars" -ForegroundColor White
Write-Host "3. Run: terraform apply -var-file=dev.tfvars" -ForegroundColor White
Write-Host "4. Get SQL password: terraform output sql_password_retrieval_command" -ForegroundColor White
Write-Host ""
Write-Host "?? Important Notes:" -ForegroundColor Yellow
Write-Host "- SQL password is AUTO-GENERATED during terraform apply" -ForegroundColor White
Write-Host "- Password is stored in Azure Key Vault automatically" -ForegroundColor White
Write-Host "- Use dev.tfvars for environment configuration" -ForegroundColor White
Write-Host "- No terraform.tfvars file needed for basic setup!" -ForegroundColor White
Write-Host ""

Pop-Location

Write-Host "Press any key to continue..." -ForegroundColor Yellow
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
